### PR TITLE
Updated changelog for v10.1.1 and v10.1.0

### PR DESCRIPTION
**Pull request by theromulans**
Thought I better keep this updated - problem currently?

ping @davidchin @icatalina @gayanhewa

### CODE REVIEW

**Review by davidchin — APPROVED** [review]

**Comment by theromulans** [comment]
Looks like I don't have write access currently @davidchin, if you wanted to merge and/or grant this access.

**Comment by davidchin** [comment]
Interesting. I'll merge it for you this time. But I'll see if I can grant you access so you can merge next time.

**Comment by theromulans** [comment]
@davidchin FYI just received this today during ng-checkout `npm run release`

> ERROR: Permission to bigcommerce/optimized-checkout-changelog.git denied to theromulans.

**Comment by davidchin** [comment]
Hey @theromulans, the permission issue should be fixed now :)

**Comment by theromulans** [comment]
Thanks mate! @davidchin

**Pull request merged**
